### ISSUE TITLE
Cannot build Android

### ISSUE THREAD

**Issue by jonathan68** [yfuks/react-native-action-sheet#14]
https://github.com/yfuks/react-native-action-sheet/commit/794cdeeba9c223a0a79d06e2b421976298bb76ef

I can't build Android because of missing **createJSModules** function.

**Comment by yfuks** [comment]
Remove 0.0.4 from you package & node_modules then:
`npm install @yfuks/react-native-action-sheet@0.0.3 --save react-native link @yfuks/react-native-action-sheet`
