### ISSUE TITLE
Build Failed in Android

### ISSUE THREAD

**Issue by wayne1203** [yfuks/react-native-action-sheet#18]
Hi, I got an error when I building the app to Android device.

I'm using React Native 0.47.1 and react-native-action-sheet 0.0.4

* What went wrong:
A problem occurred configuring project ':(at)yfuks/react-native-action-sheet'.
\> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by yfuks** [comment]
As described in the message you need to set your `ANDROID_HOME` environment variable
The react-native doc: [Configure the ANDROID_HOME environment variable](https://facebook.github.io/react-native/docs/getting-started.html#3-configure-the-android-home-environment-variable)

**Comment by wayne1203** [comment]
Sorry for asking stupid question because I just considering why it's no happening in previous.
Thank you

**Comment by chrise86** [comment]
I have `ANDROID_HOME` in my path, yet still getting this error. Any ideas?
