### ISSUE TITLE
Undefined error on Android with Expo

### ISSUE THREAD

**Issue by willc0de4food** [yfuks/react-native-action-sheet#21]
I'm getting the same error as others who have posted here while trying to use this with Expo. I've tried the auto installation instructions, but can't try the manual installation as Expo doesn't have a gradle file. Is it possible to use this module with Expo? I copy and pasted the sample code into my project, and this is the error:

> TypeError: undefined is not an object (evaluating '_reactNativeActionSheet2.default.showActionSheetWithOptions')

Versions: 
react-native 0.50.3 (https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz)
react-native-action-sheet 0.0.4

Thanks

**Comment by yfuks** [comment]
I don't think you can use it in expo since it's a native feature.
You need a full react-native environment to build this project.
