### ISSUE TITLE
React native ActionSheetIOS doesn’t seems to be centred when user changes device orientation

### ISSUE THREAD

**Issue by nvthuong** [yfuks/react-native-action-sheet#24]
Device/simulator is in portrait position. The action sheet is shown on screen and user rotates the device from portrait to landscape, the action sheet doesn’t remain centred. However, it is positioned towards left and bottom.
Please see screenshot for more details.
![screen shot 2018-01-22 at 2 26 20 pm](https://user-images.githubusercontent.com/9667961/35209435-8beb0056-ff80-11e7-936f-07df5aa0cf8f.png)
![screen shot 2018-01-22 at 2 26 11 pm](https://user-images.githubusercontent.com/9667961/35209436-8c48dde8-ff80-11e7-9ce0-9b5434f17ddc.png)

**Comment by yfuks** [comment]
Hello,

this module return the [React Native ActionSheetIOS](https://facebook.github.io/react-native/docs/actionsheetios.html) for **iOS**, not an issue with this package.
