### ISSUE TITLE
Android Studio error

### ISSUE THREAD

**Issue by alimek** [yfuks/react-native-action-sheet#25]
Hello guys,

I am getting all the time error in Android Studio:

```
Error:Unable to find module with Gradle path ':@yfuks/react-native-action-sheet' (needed by module 'app'.)
```

Anyone has faced with this issue and knows solution for this?
Generally build is building successfully, i just have this error when I do gradle sync.

**Comment by MyaElla** [comment]
Same here. Tried upgrading SDK tools but still getting it. preventing from getting a build

**Comment by alimek** [comment]
@MyaElla i am building via command line and its working :)

**Comment by LordParsley** [comment]
Same here – builds successfully using `react-native run-android` but Android Studio gradle sync gives the error above.

**Comment by alimek** [comment]
OK, just checked `README.md` and i can see that issue could be resolved by:

```
// file: android/settings.gradle
...

include ':react-native-action-sheet'
project(':react-native-action-sheet').projectDir = new File(settingsDir, '../node_modules/@yfuks/react-native-action-sheet/android')
// file: android/app/build.gradle
...
```
```
dependencies {
    ...
    compile project(':react-native-action-sheet')
}
```

Closing this issue then.

**Comment by LordParsley** [comment]
I'm not sure about closing this because `react-native link` generates the Android dependency code with as `compile project(':@yfuks/react-native-action-sheet')` most likely because the name of this plugin is set to `@yfuks/react-native-action-sheet` and not `react-native-action-sheet` over here https://github.com/yfuks/react-native-action-sheet/blob/master/package.json#L2.

I would rather suggest changing the name to be more consistent with community conventions.

**Comment by alimek** [comment]
sure, so let's keep this issue open, but like i said, could be manually fixed ;)

**Comment by yfuks** [comment]
Hey guys, sorry for the lack of response !

The module can't be renamed `react-native-action-sheet` since i don't own this name on npm...

**Comment by LordParsley** [comment]
Thanks for the feedback @yfuks – totally makes sense.

No pressure, but I see https://www.npmjs.com/package/react-native-action-sheet has:

```
Author message:
this package has been deprecated
```

so it might be worthwhile emailing the `react-native-action-sheet` owner fov42550564 (`npm owner ls react-native-action-sheet`) and support@npmjs.com to "Adopt an abandoned package"
as per https://www.npmjs.com/policies/disputes 😊

**Comment by yfuks** [comment]
Thanks @LordParsley !

Will right that email soon ! I'll keep you in touch

**Comment by yfuks** [comment]
Finally done ! Newest version is now available on npm [react-native-action-sheet](https://www.npmjs.com/package/react-native-action-sheet)

Let me know if you have any issue.

**Comment by LordParsley** [comment]
No issues – working brilliantly 👍 Thanks very much, @yfuks .
