### ISSUE TITLE
Android: Support React Native 0.56

### ISSUE THREAD

**Issue by jamesholcomb** [yfuks/react-native-action-sheet#31]
https://github.com/rmevans9/react-native-action-sheet/commit/2e5cb7e210428680495a1c100a904b781048a2e8

**Comment by skb1129** [comment]
I see the changes have been made to this repository to support RN 0.56. When will these changes be uploaded to `npm`?

**Comment by yfuks** [comment]
Done ! Sorry i was waiting for `npm` to give me access to [react-native-action-sheet](https://www.npmjs.com/package/react-native-action-sheet)

**Comment by skb1129** [comment]
Thanks a lot!
